apiVersion: apps/v1
kind: Deployment
metadata:
  name: dmm-blas-deploy
  labels:
    app: dmm-blas
  annotations:
spec:
  selector:
    matchLabels:
      app: dmm-blas
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: dmm-blas
    spec:
      containers:
      - name: dmm-blas
        image: stillwater/cndmm:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets/
        - name: config-volume
          mountPath: /configs/
      volumes:
      - name: secret-volume
        secret:
          secretName: mysecret
      - name: config-volume
        configMap:
          name: example-config               #name of our configmap object